apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: hybrid-scheduler
    tier: control-plane
  name: hybrid-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: hybrid-scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: hybrid-scheduler
        tier: control-plane
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccountName: hybrid-scheduler-account
      containers:
      - image: miadan/hybrid-scheduler:v0.0.0
        name: hybrid-scheduler
